/**
 * Extract a live article folder into content/articles/{slug}.json (sample schema).
 * Usage: node scripts/admin-render/extract_article_sample.mjs --slug how-to-choose-a-microwave-2026
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "../..");

function arg(name, fallback = "") {
  const i = process.argv.indexOf(name);
  return i >= 0 ? process.argv[i + 1] : fallback;
}

const slug = arg("--slug", "how-to-choose-a-microwave-2026");
const htmlPath = path.join(ROOT, slug, "index.html");
if (!fs.existsSync(htmlPath)) {
  console.error("Missing", htmlPath);
  process.exit(1);
}
const html = fs.readFileSync(htmlPath, "utf8");

function meta(prop) {
  const re = new RegExp(
    `<meta[^>]+(?:property|name)=["']${prop}["'][^>]+content=["']([^"']+)["']`,
    "i"
  );
  const m = html.match(re);
  return m ? m[1] : "";
}
function tag(re) {
  const m = html.match(re);
  return m ? m[1].replace(/<[^>]+>/g, "").trim() : "";
}

const title =
  meta("og:title").replace(/\s+[\u2013\u2014|-].*$/, "").trim() ||
  tag(/<title>([^<]+)<\/title>/i);
const dek = meta("og:description") || meta("description");
const cover = meta("og:image").replace(/^https?:\/\/pickora\.shop/i, "") || "";
const h1 = tag(/<h1[^>]*id=["']pk-review-title["'][^>]*>([\s\S]*?)<\/h1>/i) || title;

const amazon = [
  ...html.matchAll(/href=["'](https:\/\/(?:amzn\.to|link\.amazon)\/[^"']+)["']/gi),
].map((m) => m[1]);
const uniqueAmazon = [...new Set(amazon)];

const sample = {
  slug,
  status: "live",
  type: 2,
  title,
  metaDescription: dek.slice(0, 170),
  h1,
  dek,
  hubCategory: "Articles",
  hubUrl: "/articles/",
  chips: ["kitchen"],
  coverImage: cover,
  coverAlt: title,
  canonical: `https://pickora.shop/${slug}/`,
  affiliateLinks: uniqueAmazon.slice(0, 12),
  internalLinks: ["/articles/", "/articles/?cat=kitchen"],
  blocks: [
    {
      id: "extracted-note",
      type: "html",
      html: "<!-- Extracted sample from live HTML. Re-block in Studio for full edit. -->",
    },
  ],
  bodyHtml: "",
  faq: [],
  note: "Generated by extract_article_sample.mjs — schema reference for Studio/Worker.",
};

const outDir = path.join(ROOT, "content", "articles");
fs.mkdirSync(outDir, { recursive: true });
const outPath = path.join(outDir, `${slug}.json`);
fs.writeFileSync(outPath, JSON.stringify(sample, null, 2) + "\n", "utf8");
console.log("Wrote", outPath);
console.log("Affiliate links:", uniqueAmazon.length);
